package View.Requests;

public enum ManagerRequest {
    MANAGE_USERS,
    MANAGE_ALL_PRODUCTS,
    VIEW_DISCOUNT_CODES,
    VIEW_REQUESTS,
    MANAGE_CATEGORIES,
    VIEW_USER,
    DELETE_USER,
    CREAT_NEW_MANAGER,
    REMOVE_PRODUCT,
    VIEW_DISCOUNT_CODE,
    EDIT_DISCOUNT_CODE,
    REMOVE_DESCOUNT_CODE,
    VIEW_REQUEST_DETAILS,
    ACCEPT_REQUEST,
    DECLINE_REQUEST,
    EDIT_CATEGORY,
    ADD_CATEGORY,
    REMOVE_CATEGORY
}
