package View.Requests;

public enum SellerRequest{
    VIEW_COMPANY_INFORMATION,
    VIEW_SALES_HISTORY,
    MANAGE_PRODUCTS,
    SHOW_CATEGORIES,
    VIEW_SELLERS_SALES,
    VIEW_BALANCE,
    VIEW_PRODUCT_BUYERS,
    EDIT_PRODUCT,
    ADD_PRODUCT,
    VIEW_SALE,
    REMOVE_PRODUCT,
    EDIT_SALE,
    ADD_SALE,
    VIEW_SALE_HELP
}
